### ISSUE TITLE
启动app时报错

### ISSUE THREAD

**Issue by kouhengsheng** [GiitSmile/ImitateNetEasyCloud#2]
下载这个demo运行时闪退，logcat报的错是You need to use a Theme.AppCompat theme。在清单文件中Application节点中添加android:theme="@style/Theme.AppCompat"这个主题就不闪退了。

**Comment by DreamClimb** [comment]
添加主题后报
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.stest.neteasycloud/com.stest.neteasycloud.SplashActivity}: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 6: TypedValue{t=0x2/d=0x101009b a=1}
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2449)
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2509)
                                                                            at android.app.ActivityThread.access$1000(ActivityThread.java:153)
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1373)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                            at android.os.Looper.loop(Looper.java:154)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5524)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:740)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:630)
                                                                         Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 6: TypedValue{t=0x2/d=0x101009b a=1}
                                                                            at android.content.res.TypedArray.getColorStateList(TypedArray.java:484)
                                                                            at android.widget.TextView.<init>(TextView.java:753)
                                                                            at android.widget.TextView.<init>(TextView.java:674)
                                                                            at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:62)
                                                                            at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:58)
                                                                            at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:54)
                                                                            at android.support.v7.widget.Toolbar.setTitle(Toolbar.java:756)
                                                                            at android.support.v7.widget.ToolbarWidgetWrapper.setTitleInt(ToolbarWidgetWrapper.java:261)
                                                                            at android.support.v7.widget.ToolbarWidgetWrapper.setWindowTitle(ToolbarWidgetWrapper.java:243)
                                                                            at android.support.v7.widget.ActionBarOverlayLayout.setWindowTitle(ActionBarOverlayLayout.java:615)
                                                                            at android.support.v7.app.AppCompatDelegateImplV9.onTitleChanged(AppCompatDelegateImplV9.java:636)
                                                                            at android.support.v7.app.AppCompatDelegateImplV9.ensureSubDecor(AppCompatDelegateImplV9.java:333)
                                                                            at android.support.v7.app.AppCompatDelegateImplV9.onPostCreate(AppCompatDelegateImplV9.java:176)
                                                                            at android.support.v7.app.AppCompatActivity.onPostCreate(AppCompatActivity.java:98)
                                                                            at android.app.Instrumentation.callActivityOnPostCreate(Instrumentation.java:1189)
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2431)
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2509) 
                                                                            at android.app.ActivityThread.access$1000(ActivityThread.java:153) 
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1373) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                            at android.os.Looper.loop(Looper.java:154) 
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5524) 
                                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:740) 
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:630)

**Comment by kouhengsheng** [comment]
方不方便把你的整个工程压缩后发给我，我的邮箱是ykkssk@163.com

**Comment by Litten1106** [comment]
不好意思因为太久没有时间去维护本地也没有相关版本，所有的资源都在GitHub上请自己下载，所需时间也不会很长

2017-07-18 19:18 GMT+08:00, kouhengsheng <notifications@github.com>:
